export const foods = [
	{
		name: "Hamburger",
		icon: "🍔",
		category: "Fast Food",
		price: 8.99,
	},
	{
		name: "Pizza Margherita",
		icon: "🍕",
		category: "Italian",
		price: 10.75,
	},
	{
		name: "Tacos al Pastor",
		icon: "🌮",
		category: "Mexican",
		price: 9.5,
	},
	{
		name: "Caesar Salad",
		icon: "🥗",
		category: "Healthy",
		price: 7.99,
	},
	{
		name: "Assorted Sushi",
		icon: "🍣",
		category: "Japanese",
		price: 15.99,
	},
	{
		name: "Hot Dog",
		icon: "🌭",
		category: "Fast Food",
		price: 5.99,
	},
	{
		name: "Spaghetti Bolognese",
		icon: "🍝",
		category: "Italian",
		price: 12.99,
	},
	{
		name: "Quesadillas",
		icon: "🧀",
		category: "Mexican",
		price: 8.25,
	},
	{
		name: "Quinoa Salad",
		icon: "🥗",
		category: "Healthy",
		price: 9.75,
	},
	{
		name: "Salmon Sashimi",
		icon: "🍣",
		category: "Japanese",
		price: 18.5,
	},
	{
		name: "Cheeseburger",
		icon: "🍔",
		category: "Fast Food",
		price: 10.5,
	},
	{
		name: "Lasagna",
		icon: "🍝",
		category: "Italian",
		price: 14.25,
	},
	{
		name: "Nachos with Guacamole",
		icon: "🌮",
		category: "Mexican",
		price: 8.99,
	},
	{
		name: "Chicken Teriyaki Bowl",
		icon: "🍚",
		category: "Japanese",
		price: 11.99,
	},
	{
		name: "Fruit Smoothie",
		icon: "🍹",
		category: "Healthy",
		price: 6.5,
	},
];